insert into public.site_content (id, hero_tagline, hero_title, hero_subtitle, hero_cta)
values (
  'global',
  'Student Startups',
  'Build something real before graduation.',
  'Find teammates, test ideas, launch products, and learn how startups actually work while you are still in school.',
  'Start Building'
)
on conflict (id) do update
set hero_tagline = excluded.hero_tagline,
    hero_title = excluded.hero_title,
    hero_subtitle = excluded.hero_subtitle,
    hero_cta = excluded.hero_cta;

insert into public.site_copy (key, value_en, value_ko)
values
  ('nav.intro', 'Start Here', '시작점'),
  ('nav.value', 'Why It Works', '왜 되는지'),
  ('nav.process', 'Build Cycle', '빌드 사이클'),
  ('nav.proof', 'Results', '결과'),
  ('nav.cta', 'Start Building', '직접 시작'),
  ('nav.explore', 'Pages', '페이지'),
  ('hero.secondaryCta', 'How We Build', '어떻게 굴러가는지'),
  ('valueProp.kicker', 'Why It Works', '왜 되는지'),
  ('valueProp.title', 'Built for students who want to ship.', '만들고 싶은 학생에게 맞춘 구조'),
  ('valueProp.subtitle', 'Real teams, real deadlines, real customers. The whole system is designed to get ideas out of the group chat and into the world.', '실제 팀, 실제 마감, 실제 결과. 아이디어를 말로만 끝내지 않게 설계했습니다.'),
  ('valueProp.oneTitle', 'Clear build system', '끝까지 가는 프로세스'),
  ('valueProp.oneDesc', 'Move from idea to launch with a process that keeps teams shipping.', '아이디어에서 출시까지 흐름이 끊기지 않도록 단계가 잡혀 있습니다.'),
  ('valueProp.twoTitle', 'Real startup roles', '스타트업처럼 역할 분담'),
  ('valueProp.twoDesc', 'Own marketing, production, finance, or design and see how each part affects the business.', '마케팅, 생산, 재무, 디자인을 직접 맡으면서 비즈니스 전체를 이해하게 됩니다.'),
  ('valueProp.threeTitle', 'Proof you can show', '남는 건 결과물'),
  ('valueProp.threeDesc', 'Leave with launches, revenue, experiments, and project history that actually means something.', '출시 기록, 매출, 실험, 프로젝트 히스토리가 실제로 남습니다.'),
  ('workflow.kicker', 'Build Cycle', '빌드 사이클'),
  ('workflow.title', 'How ideas turn into launches here.', '아이디어가 런치까지 가는 방식'),
  ('workflow.subtitle', 'Every team works through the same cycle so ideas get tested, built, launched, and reviewed in public.', '모든 팀이 같은 흐름으로 검증하고 만들고 출시합니다. 그래서 말보다 실행이 앞섭니다.'),
  ('workflow.steps.step1Title', 'Pick a real problem', '진짜 문제 고르기'),
  ('workflow.steps.step1Desc', 'Start with a problem people actually have.', '사람들이 실제로 겪는 문제부터 잡습니다.'),
  ('workflow.steps.step2Title', 'Check the market', '시장 보기'),
  ('workflow.steps.step2Desc', 'Figure out who wants it and why.', '누가 왜 원하는지 먼저 확인합니다.'),
  ('workflow.steps.step3Title', 'Build the first version', '첫 버전 만들기'),
  ('workflow.steps.step3Desc', 'Ship something simple enough to test fast.', '빠르게 테스트할 수 있을 정도로 먼저 만듭니다.'),
  ('workflow.steps.step4Title', 'Test with real people', '직접 검증하기'),
  ('workflow.steps.step4Desc', 'Get feedback early and cut what does not work.', '실제 피드백으로 바로 고칩니다.'),
  ('workflow.steps.step5Title', 'Tighten production', '생산 다듬기'),
  ('workflow.steps.step5Desc', 'Improve the product, the workflow, and the quality.', '제품, 품질, 작업 방식을 정리합니다.'),
  ('workflow.steps.step6Title', 'Launch and sell', '출시하고 팔기'),
  ('workflow.steps.step6Desc', 'Put it in front of customers and see what happens.', '시장에 내놓고 반응을 봅니다.'),
  ('workflow.steps.step7Title', 'Review the numbers', '숫자 보기'),
  ('workflow.steps.step7Desc', 'Measure sales, costs, donations, and what to do next.', '매출, 비용, 기부, 다음 액션을 정리합니다.'),
  ('impactPreview.title', 'Real work. Real numbers.', '진짜로 만든 결과'),
  ('impactPreview.subtitle', 'See what got launched, what made money, and what actually moved.', '무엇이 나갔고, 얼마가 팔렸는지 바로 확인할 수 있습니다.'),
  ('featured.title', 'Featured builds', '주요 프로젝트'),
  ('featured.subtitle', 'A few of the projects students have already taken past the idea stage.', '아이디어 단계에서 끝나지 않고 실제로 밖으로 나간 작업들입니다.'),
  ('featured.viewAll', 'See All Projects', '프로젝트 전체 보기'),
  ('proof.kicker', 'Results', '결과'),
  ('cta.title', 'Stop waiting to call yourself a founder.', '창업은 나중이 아니라 지금 시작하는 겁니다.'),
  ('cta.subtitle', 'If you want teammates, deadlines, launches, and real feedback, this is where you start.', '팀도, 마감도, 출시도, 피드백도 필요하다면 여기서 바로 시작하세요.'),
  ('cta.button', 'Join the Build', '빌드에 합류하기'),
  ('about.title', 'How Student Startups works', 'Student Startups는 이렇게 굴러갑니다'),
  ('about.subtitle', 'This is not a pitch club. It is a student-run system for testing ideas, building products, and learning through execution.', '피치만 하는 동아리가 아닙니다. 학생이 직접 만들고, 팔아보고, 숫자로 배우는 실행 시스템입니다.'),
  ('projects.title', 'What we are building', '지금 만들고 있는 것들'),
  ('projects.subtitle', 'Browse active projects, shipped launches, and ideas moving through the pipeline.', '진행 중인 프로젝트와 이미 출시된 작업을 한곳에서 봅니다.'),
  ('projects.viewDetails', 'Open Project', '프로젝트 보기'),
  ('projects.noProjects', 'Nothing matches this filter yet.', '지금 선택한 조건에는 아직 없습니다.'),
  ('impact.title', 'Impact', '임팩트'),
  ('impact.subtitle', 'Track what got launched, what made money, and how the platform is growing.', '무엇이 출시됐고, 얼마가 돌았는지, 팀이 어떻게 커지는지 확인하세요.'),
  ('impact.revenueBody', 'See which launches turned into sales instead of staying ideas.', '아이디어가 실제 매출로 이어졌는지 볼 수 있습니다.'),
  ('impact.donationBody', 'Compare how much each launch has given back.', '프로젝트별로 얼마나 다시 환원했는지 비교합니다.'),
  ('impact.memberBody', 'Watch the team grow over time and plan around real capacity.', '팀 규모가 어떻게 커지는지 보면서 다음 운영을 준비합니다.'),
  ('impact.stageBody', 'See where teams are stuck, moving, or ready to launch.', '어느 단계에 프로젝트가 몰려 있는지 바로 파악할 수 있습니다.'),
  ('shop.subtitle', 'Buy what students are actually launching and see the work behind it.', '학생 팀이 실제로 출시한 제품을 보고, 구매하고, 결과까지 확인해보세요.'),
  ('shop.viewProduct', 'Open Product', '상품 보기'),
  ('shop.emptyCart', 'Your cart is empty.', '담아둔 상품이 아직 없습니다.'),
  ('shop.continueShopping', 'Keep Browsing', '다른 상품 보기'),
  ('shop.processing', 'Sending order...', '주문 보내는 중...'),
  ('shop.deliveryNote', 'Pickup / delivery note (optional)', '전달 메모 (선택)'),
  ('shop.relatedProducts', 'More from the shop', '같이 볼 만한 제품'),
  ('shop.noProducts', 'Nothing is live in the shop yet.', '지금 공개된 상품이 없습니다.'),
  ('shop.productNotFound', 'That product is not available.', '이 상품은 지금 볼 수 없습니다.'),
  ('contact.title', 'Let''s talk', '이야기해봅시다'),
  ('contact.subtitle', 'Questions, partnerships, or ideas you want to build with us? Send the note.', '함께 만들고 싶은 것, 제안, 질문이 있다면 편하게 보내주세요.'),
  ('contact.subject', 'What are you reaching out about?', '어떤 내용인가요?'),
  ('contact.send', 'Send Note', '문의 보내기'),
  ('contact.success', 'Thanks — we got your message and will reply soon.', '메시지 잘 받았습니다. 곧 답장드릴게요.'),
  ('portal.subtitle', 'Your meetings, roles, team history, and contribution record live here.', '미팅 기록, 맡은 역할, 팀 히스토리, 기여 내용이 한곳에 모입니다.'),
  ('portal.dashboard', 'Home Base', '홈 베이스'),
  ('portal.contributionSummary', 'Contribution points this term', '이번 학기 기여 포인트'),
  ('portal.noMeetings', 'No meeting records yet.', '아직 미팅 기록이 없습니다.'),
  ('login.title', 'Sign in', '로그인'),
  ('login.subtitle', 'Use your member account to open your portal. Admin access lives here too.', '멤버 포털과 관리자 페이지에 들어가는 계정입니다.'),
  ('login.memberTitle', 'Member login', '멤버 로그인'),
  ('login.memberDesc', 'Open your portal, meeting notes, and contribution history.', '포털, 미팅 기록, 기여 내역을 확인합니다.'),
  ('login.adminDesc', 'Manage members, projects, shop, orders, and messages.', '멤버, 프로젝트, 샵, 주문, 문의를 관리합니다.'),
  ('login.memberHint', 'Already have an account?', '이미 계정이 있나요?'),
  ('login.memberHintAlt', 'Need an account?', '계정이 아직 없나요?'),
  ('login.adminHint', 'Admin access is restricted.', '관리자 계정만 접근할 수 있습니다.'),
  ('login.redirecting', 'Connecting to Google...', 'Google로 연결하는 중...'),
  ('forgotPassword.subtitle', 'Enter your email and we will send a code so you can set a new password.', '이메일을 입력하면 새 비밀번호를 설정할 수 있는 코드를 보내드립니다.'),
  ('forgotPassword.send', 'Send reset code', '재설정 코드 보내기'),
  ('forgotPassword.sent', 'Check your email for the 6-digit reset code.', '메일함에서 6자리 재설정 코드를 확인해주세요.'),
  ('resetPassword.title', 'Choose a new password', '새 비밀번호 정하기'),
  ('resetPassword.subtitle', 'Set the password you want to use from now on.', '앞으로 사용할 비밀번호를 설정하세요.'),
  ('resetPassword.update', 'Save new password', '새 비밀번호 저장'),
  ('footer.description', 'Build something real before graduation. Student Startups is where students test ideas, launch products, and learn by doing.', '졸업하기 전에 진짜 서비스를 만들어보세요. Student Startups는 학생이 팀을 꾸리고, 제품을 내놓고, 직접 배워보는 곳입니다.'),
  ('footer.quickLinks', 'Navigate', '둘러보기'),
  ('footer.programs', 'Access', '바로가기'),
  ('footer.cta', 'Start Building', '직접 만들기'),
  ('footer.viewWork', 'See Projects', '프로젝트 보기'),
  ('common.learnMore', 'See How It Works', '어떻게 굴러가는지 보기')
on conflict (key) do update
set value_en = excluded.value_en,
    value_ko = excluded.value_ko;
