insert into public.site_content (
  id,
  hero_tagline,
  hero_title,
  hero_subtitle,
  hero_cta,
  total_revenue,
  total_profit,
  total_donated,
  active_members
)
values (
  'global',
  'Student Startups',
  'A serious place for early builders.',
  'Student Startups is a platform for students developing real products, operating disciplined teams, and building a record that can be examined.',
  'Review the Work',
  '24850',
  '12430',
  '6200',
  '84'
)
on conflict (id) do update
set hero_tagline = excluded.hero_tagline,
    hero_title = excluded.hero_title,
    hero_subtitle = excluded.hero_subtitle,
    hero_cta = excluded.hero_cta;

insert into public.site_copy (key, value_en, value_ko)
values
  ('nav.intro', 'Overview', '개요'),
  ('nav.value', 'Structure', '구조'),
  ('nav.process', 'Method', '운영 방식'),
  ('nav.proof', 'Record', '기록'),
  ('nav.cta', 'Contact', '문의'),
  ('nav.explore', 'Pages', '페이지'),
  ('hero.secondaryCta', 'How It Operates', '어떻게 운영되는지 보기'),
  ('valueProp.kicker', 'Structure', '구조'),
  ('valueProp.title', 'A serious platform for early builders.', '일찍 시작하는 빌더를 위한 진지한 플랫폼'),
  ('valueProp.subtitle', 'Work happens inside real constraints: roles, timelines, budgets, and outcomes.', '여기서는 역할, 일정, 예산, 결과를 실제 기준으로 다룹니다.'),
  ('valueProp.oneTitle', 'Structured execution', '구조화된 실행'),
  ('valueProp.oneDesc', 'Ideas move through a defined process with accountability at each stage.', '각 단계마다 책임이 분명한 프로세스를 거칩니다.'),
  ('valueProp.twoTitle', 'Operating range', '운영 전반에 대한 경험'),
  ('valueProp.twoDesc', 'Work spans marketing, production, finance, and design rather than a single narrow function.', '한 기능에 머무르지 않고 마케팅, 생산, 재무, 디자인 전반을 다룹니다.'),
  ('valueProp.threeTitle', 'Durable record', '남는 기록'),
  ('valueProp.threeDesc', 'The result is not participation but work, numbers, and decisions that hold up outside the institution.', '남는 것은 참여 경험이 아니라 밖에서도 설명 가능한 결과, 숫자, 판단입니다.'),
  ('workflow.kicker', 'Method', '운영 방식'),
  ('workflow.title', 'A disciplined operating cycle.', '검토 가능한 운영 사이클'),
  ('workflow.subtitle', 'Research, build, release, and review with clear responsibility at each stage.', '리서치, 제작, 공개, 검토를 각 단계의 책임과 함께 진행합니다.'),
  ('workflow.steps.step1Title', 'Define the problem', '문제 정의'),
  ('workflow.steps.step1Desc', 'Start with a problem worth solving.', '해결할 가치가 있는 문제부터 정합니다.'),
  ('workflow.steps.step2Title', 'Test demand', '수요 확인'),
  ('workflow.steps.step2Desc', 'Check who wants it and why.', '누가 왜 원하는지 먼저 봅니다.'),
  ('workflow.steps.step3Title', 'Build the first version', '첫 버전 제작'),
  ('workflow.steps.step3Desc', 'Make something clear enough to evaluate.', '평가할 수 있을 정도의 형태를 만듭니다.'),
  ('workflow.steps.step4Title', 'Review with users', '사용자 검토'),
  ('workflow.steps.step4Desc', 'Put the work in front of real people and revise accordingly.', '실제 반응을 보고 바로 수정합니다.'),
  ('workflow.steps.step5Title', 'Refine operations', '운영 정비'),
  ('workflow.steps.step5Desc', 'Tighten quality, process, and execution.', '품질, 과정, 실행을 다듬습니다.'),
  ('workflow.steps.step6Title', 'Go to market', '시장에 내놓기'),
  ('workflow.steps.step6Desc', 'Release the product and observe the response.', '공개하고 반응을 확인합니다.'),
  ('workflow.steps.step7Title', 'Measure the outcome', '결과 측정'),
  ('workflow.steps.step7Desc', 'Track revenue, costs, donations, and what follows next.', '매출, 비용, 기부, 다음 판단을 정리합니다.'),
  ('impactPreview.title', 'A public record of the work.', '기록으로 남는 결과'),
  ('impactPreview.subtitle', 'Projects, revenue, donations, and growth, presented directly.', '프로젝트, 매출, 기부, 성장 흐름을 그대로 보여줍니다.'),
  ('featured.title', 'Selected work', '선별된 프로젝트'),
  ('featured.subtitle', 'Current and completed projects with measurable output.', '현재 진행 중이거나 이미 결과를 낸 작업들입니다.'),
  ('featured.viewAll', 'Review All Projects', '프로젝트 전체 보기'),
  ('proof.kicker', 'Record', '기록'),
  ('cta.title', 'Built for people with standards.', '기준을 중요하게 생각하는 사람을 위한 플랫폼입니다.'),
  ('cta.subtitle', 'Student Startups is designed for students who value judgment, responsibility, and work that can withstand review.', 'Student Startups는 판단력, 책임, 검토 가능한 결과를 중요하게 보는 학생을 위해 설계되어 있습니다.'),
  ('cta.button', 'Request Access', '참여 문의'),
  ('about.title', 'About Student Startups', 'Student Startups 소개'),
  ('about.subtitle', 'Student Startups is built around real work: products, responsibility, constraints, and outcomes.', 'Student Startups는 실제 업무를 중심에 둡니다. 제품, 책임, 제약, 결과가 모두 포함됩니다.'),
  ('projects.title', 'Projects', '프로젝트'),
  ('projects.subtitle', 'Work in progress, shipped launches, and projects under review.', '진행 중인 작업, 이미 공개된 결과, 검토 중인 프로젝트를 봅니다.'),
  ('projects.viewDetails', 'Review Project', '프로젝트 검토'),
  ('projects.noProjects', 'No projects match this filter.', '이 조건에 맞는 프로젝트가 없습니다.'),
  ('impact.title', 'Impact', '임팩트'),
  ('impact.subtitle', 'A running record of launches, revenue, donations, and team growth.', '출시, 매출, 기부, 팀 성장에 대한 누적 기록입니다.'),
  ('impact.revenueBody', 'Revenue is tracked to show whether the work holds up outside the room.', '이 작업이 실제 시장에서도 통하는지 매출로 확인합니다.'),
  ('impact.donationBody', 'Donation data shows which projects are producing surplus worth returning.', '어떤 프로젝트가 환원 가능한 잉여를 만들었는지 보여줍니다.'),
  ('impact.memberBody', 'Growth is measured so capacity planning remains grounded.', '성장 속도를 수치로 보고 운영 규모를 판단합니다.'),
  ('impact.stageBody', 'Stage distribution shows where projects require the most attention.', '어느 단계에 관리와 지원이 더 필요한지 한눈에 파악할 수 있습니다.'),
  ('shop.subtitle', 'Products developed and operated by student teams under real operating constraints.', '학생 팀이 실제 운영 기준 아래 다루는 제품입니다.'),
  ('shop.viewProduct', 'Review Product', '상품 검토'),
  ('shop.emptyCart', 'No items in cart.', '장바구니에 담긴 상품이 없습니다.'),
  ('shop.continueShopping', 'Return to Shop', '스토어로 돌아가기'),
  ('shop.processing', 'Submitting...', '제출 중...'),
  ('shop.deliveryNote', 'Pickup or delivery note (optional)', '수령 또는 전달 메모 (선택)'),
  ('shop.relatedProducts', 'Related Products', '관련 상품'),
  ('shop.noProducts', 'No products are available at the moment.', '현재 공개된 상품이 없습니다.'),
  ('shop.productNotFound', 'This product is not available.', '이 상품은 현재 볼 수 없습니다.'),
  ('contact.title', 'Contact', '문의'),
  ('contact.subtitle', 'Partnerships, platform questions, and institutional inquiries.', '협업, 플랫폼 문의, 대외 문의는 이곳으로 보내주세요.'),
  ('contact.subject', 'Subject', '제목'),
  ('contact.send', 'Send Inquiry', '문의 보내기'),
  ('contact.success', 'Your message has been received. We will reply shortly.', '메시지가 접수되었습니다. 곧 답장드리겠습니다.'),
  ('portal.subtitle', 'Meetings, roles, attendance, and contribution history in one place.', '미팅, 역할, 출석, 기여 기록을 한곳에서 봅니다.'),
  ('portal.dashboard', 'Overview', '개요'),
  ('portal.contributionSummary', 'Contribution total this term', '이번 학기 기여 총점'),
  ('portal.noMeetings', 'No meeting records yet.', '아직 미팅 기록이 없습니다.'),
  ('login.title', 'Sign In', '로그인'),
  ('login.subtitle', 'Access the member portal or administrative tools.', '멤버 포털과 관리자 도구에 접근하는 계정입니다.'),
  ('login.memberTitle', 'Member access', '멤버 접근'),
  ('login.memberDesc', 'Attendance, roles, meeting notes, and contribution history.', '출석, 역할, 미팅 기록, 기여 내역을 확인합니다.'),
  ('login.adminDesc', 'Members, projects, shop, orders, and messaging.', '멤버, 프로젝트, 스토어, 주문, 메시지를 관리합니다.'),
  ('login.memberHint', 'Have an account?', '이미 계정이 있나요?'),
  ('login.memberHintAlt', 'Need access?', '접근 권한이 필요한가요?'),
  ('login.adminHint', 'Administrative access is restricted.', '관리자 접근은 제한되어 있습니다.'),
  ('login.redirecting', 'Returning from Google...', 'Google에서 돌아오는 중...'),
  ('forgotPassword.subtitle', 'Enter your email and we will send a 6-digit code to reset your password.', '이메일을 입력하면 비밀번호 재설정용 6자리 코드를 보내드립니다.'),
  ('forgotPassword.send', 'Send code', '코드 보내기'),
  ('forgotPassword.sent', 'Check your email for the reset code.', '메일함에서 재설정 코드를 확인해주세요.'),
  ('resetPassword.title', 'Set a new password', '새 비밀번호 설정'),
  ('resetPassword.subtitle', 'Choose the password you would like to use going forward.', '앞으로 사용할 비밀번호를 정해주세요.'),
  ('resetPassword.update', 'Save password', '비밀번호 저장'),
  ('footer.description', 'A platform for students working on products with real responsibility, measurable outcomes, and standards that hold up under review.', '학생이 이른 시점부터 제품, 팀, 숫자를 실제 기준으로 다루는 플랫폼입니다.'),
  ('footer.quickLinks', 'Pages', '페이지'),
  ('footer.programs', 'Access', '접속'),
  ('footer.cta', 'Request Access', '참여 문의'),
  ('footer.viewWork', 'Review Projects', '프로젝트 보기'),
  ('common.learnMore', 'How It Operates', '어떻게 운영되는지 보기')
on conflict (key) do update
set value_en = excluded.value_en,
    value_ko = excluded.value_ko;
