import type { Project, Product, WorkflowStep, ImpactMetric, TeamInfo, MemberProfile } from '@/types';

export const workflowSteps: WorkflowStep[] = [
  { id: 1, titleEn: 'Idea Definition', titleKo: '아이디어 정의', descEn: 'Brainstorm and validate business concepts.', descKo: '비즈니스 컨셉을 구상하고 검증합니다.', icon: 'lightbulb' },
  { id: 2, titleEn: 'Market Research', titleKo: '시장 조사', descEn: 'Analyze demographics and market opportunity.', descKo: '타겟 인구와 시장 기회를 분석합니다.', icon: 'search' },
  { id: 3, titleEn: 'MVP Development', titleKo: 'MVP 개발', descEn: 'Build the minimum viable product.', descKo: '최소 기능 제품을 개발합니다.', icon: 'layers' },
  { id: 4, titleEn: 'Testing', titleKo: '테스트', descEn: 'Gather feedback and iterate.', descKo: '피드백을 수집하고 반복합니다.', icon: 'flask' },
  { id: 5, titleEn: 'Production', titleKo: '생산', descEn: 'Scale manufacturing and quality control.', descKo: '제조를 확장하고 품질을 관리합니다.', icon: 'factory' },
  { id: 6, titleEn: 'Marketing & Sales', titleKo: '마케팅 & 판매', descEn: 'Launch campaigns and drive revenue.', descKo: '캠페인을 시작하고 수익을 창출합니다.', icon: 'megaphone' },
  { id: 7, titleEn: 'Measurement', titleKo: '성과 측정', descEn: 'Evaluate and plan next steps.', descKo: '성과를 평가하고 다음을 계획합니다.', icon: 'chart' },
];

export const impactMetrics: ImpactMetric[] = [
  { labelEn: 'Total Revenue', labelKo: '총 매출', value: 24850, prefix: '$' },
  { labelEn: 'Net Profit', labelKo: '순이익', value: 12430, prefix: '$' },
  { labelEn: 'Donated to Causes', labelKo: '기부금', value: 6200, prefix: '$' },
  { labelEn: 'Active Members', labelKo: '활동 멤버', value: 84, suffix: '+' },
];

export const teamInfos: TeamInfo[] = [
  { nameEn: 'Marketing', nameKo: '마케팅', descEn: 'Brand storytelling, campaigns, and customer engagement through creative strategies.', descKo: '브랜드 스토리텔링, 캠페인, 창의적 전략을 통한 고객 참여.', icon: 'megaphone', color: 'from-rose-500 to-orange-400' },
  { nameEn: 'Production', nameKo: '생산', descEn: 'Product development from prototyping through manufacturing with quality assurance.', descKo: '프로토타이핑부터 품질 보증 제조까지 제품 개발.', icon: 'hammer', color: 'from-blue-500 to-cyan-400' },
  { nameEn: 'Finance', nameKo: '재무', descEn: 'Budget management, revenue tracking, expense analysis, and donation allocation.', descKo: '예산 관리, 수입 추적, 지출 분석, 기부 배분.', icon: 'piggybank', color: 'from-emerald-500 to-teal-400' },
  { nameEn: 'Design', nameKo: '디자인', descEn: 'Product aesthetics, packaging, brand identity, and user-centered principles.', descKo: '제품 미학, 패키징, 브랜드 아이덴티티, 사용자 중심 원칙.', icon: 'palette', color: 'from-violet-500 to-purple-400' },
];

export const projects: Project[] = [
  { id: 'p1', name: 'EcoBag Initiative', description: 'Reusable canvas tote bags with original student artwork, promoting sustainability on campus.', stage: 7, stageName: 'Completed', revenue: 2400, expenses: 960, profit: 1440, donation: 360, donationPercent: 25, team: [{ role: 'Marketing', members: ['Jisoo K.', 'Ethan L.'] }, { role: 'Production', members: ['Mina C.'] }, { role: 'Finance', members: ['Daniel P.'] }, { role: 'Design', members: ['Soojin H.'] }], image: 'https://images.unsplash.com/photo-1597484661973-ee6cd0b6482c?w=600&h=400&fit=crop', startDate: '2025-01-15', category: 'Sustainability', term: 'Term 1 (2025)' },
  { id: 'p2', name: 'Student Planner Pro', description: 'Premium academic planners designed by students, featuring productivity templates and goal tracking.', stage: 6, stageName: 'Sales', revenue: 1800, expenses: 720, profit: 1080, donation: 216, donationPercent: 20, team: [{ role: 'Marketing', members: ['Ryan K.'] }, { role: 'Production', members: ['Yuna S.', 'James W.'] }, { role: 'Finance', members: ['Hana J.'] }, { role: 'Design', members: ['Olivia T.'] }], image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=400&fit=crop', startDate: '2025-02-01', category: 'Stationery', term: 'Term 1 (2025)' },
  { id: 'p3', name: 'Campus Coffee Co.', description: 'Specialty coffee blends sourced ethically, roasted locally, and branded with campus culture.', stage: 7, stageName: 'Completed', revenue: 3200, expenses: 1600, profit: 1600, donation: 480, donationPercent: 30, team: [{ role: 'Marketing', members: ['Soyeon L.'] }, { role: 'Production', members: ['Max R.', 'Jihoon P.'] }, { role: 'Finance', members: ['Emma D.'] }, { role: 'Design', members: ['Taemin K.'] }], image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop', startDate: '2024-11-10', category: 'Food & Beverage', term: 'Term 4 (2026)' },
  { id: 'p4', name: 'Artisan Candle Workshop', description: 'Hand-poured soy candles with unique scents inspired by seasonal campus landscapes.', stage: 7, stageName: 'Completed', revenue: 1500, expenses: 525, profit: 975, donation: 195, donationPercent: 20, team: [{ role: 'Marketing', members: ['Dahyun M.'] }, { role: 'Production', members: ['Liam B.'] }, { role: 'Finance', members: ['Suji C.'] }, { role: 'Design', members: ['Ava W.'] }], image: 'https://images.unsplash.com/photo-1602607469288-db8e02f6fee3?w=600&h=400&fit=crop', startDate: '2025-03-05', category: 'Lifestyle', term: 'Term 1 (2025)' },
  { id: 'p5', name: 'Tech Accessories Hub', description: 'Custom-designed phone stands, cable organizers, and desk accessories for students.', stage: 4, stageName: 'Testing', revenue: 800, expenses: 480, profit: 320, donation: 64, donationPercent: 20, team: [{ role: 'Marketing', members: ['Noah S.'] }, { role: 'Production', members: ['Minji K.'] }, { role: 'Finance', members: ['Lucas G.'] }, { role: 'Design', members: ['Chaeyoung P.'] }], image: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600&h=400&fit=crop', startDate: '2025-04-12', category: 'Tech', term: 'Term 2 (2025)' },
  { id: 'p6', name: 'Handmade Jewelry Line', description: 'Minimalist jewelry pieces crafted from sustainable materials with student-designed motifs.', stage: 6, stageName: 'Sales', revenue: 2100, expenses: 840, profit: 1260, donation: 378, donationPercent: 30, team: [{ role: 'Marketing', members: ['Seoyeon J.'] }, { role: 'Production', members: ['Ella V.'] }, { role: 'Finance', members: ['Woojin K.'] }, { role: 'Design', members: ['Isabella R.'] }], image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=400&fit=crop', startDate: '2025-01-28', category: 'Fashion', term: 'Term 1 (2025)' },
  { id: 'p7', name: 'Sustainable Stationery', description: 'Eco-friendly notebooks and pens made from recycled materials with plantable seed covers.', stage: 3, stageName: 'Developing', revenue: 200, expenses: 350, profit: -150, donation: 0, donationPercent: 15, team: [{ role: 'Marketing', members: ['Hayoon L.'] }, { role: 'Production', members: ['Caleb N.'] }, { role: 'Finance', members: ['Nayeon B.'] }, { role: 'Design', members: ['Oscar M.'] }], image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop', startDate: '2025-05-20', category: 'Stationery', term: 'Term 2 (2025)' },
  { id: 'p8', name: 'School Merch Store', description: 'Premium school-branded apparel including hoodies, caps, and accessories with modern designs.', stage: 7, stageName: 'Completed', revenue: 4500, expenses: 2250, profit: 2250, donation: 675, donationPercent: 30, team: [{ role: 'Marketing', members: ['Eunji S.', 'Tyler H.'] }, { role: 'Production', members: ['Jiho K.'] }, { role: 'Finance', members: ['Sophie C.'] }, { role: 'Design', members: ['Hyunjin A.'] }], image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=400&fit=crop', startDate: '2024-09-01', category: 'Apparel', term: 'Term 3 (2026)' },
  { id: 'p9', name: 'Organic Snack Box', description: 'Curated monthly snack boxes featuring local organic treats and healthy study fuel.', stage: 5, stageName: 'Production', revenue: 1200, expenses: 660, profit: 540, donation: 108, donationPercent: 20, team: [{ role: 'Marketing', members: ['Yejin P.'] }, { role: 'Production', members: ['Marcus L.'] }, { role: 'Finance', members: ['Somin K.'] }, { role: 'Design', members: ['Aiden J.'] }], image: 'https://images.unsplash.com/photo-1499028344343-cd173ffc68a9?w=600&h=400&fit=crop', startDate: '2025-02-14', category: 'Food & Beverage', term: 'Term 1 (2025)' },
  { id: 'p10', name: 'Digital Art Prints', description: 'Limited-edition art prints created by student digital artists, printed on archival paper.', stage: 4, stageName: 'Testing', revenue: 600, expenses: 180, profit: 420, donation: 84, donationPercent: 20, team: [{ role: 'Marketing', members: ['Jiwoo H.'] }, { role: 'Production', members: ['Grace F.'] }, { role: 'Finance', members: ['Sunwoo K.'] }, { role: 'Design', members: ['Chloe B.'] }], image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&h=400&fit=crop', startDate: '2025-03-22', category: 'Art', term: 'Term 2 (2025)' },
  { id: 'p11', name: 'Campus Map App', description: 'Interactive digital campus guide with event listings, food reviews, and navigation.', stage: 2, stageName: 'Research', revenue: 0, expenses: 120, profit: -120, donation: 0, donationPercent: 10, team: [{ role: 'Marketing', members: ['Doyeon S.'] }, { role: 'Production', members: ['Kevin T.'] }, { role: 'Finance', members: ['Areum J.'] }, { role: 'Design', members: ['Leo W.'] }], image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop', startDate: '2025-06-01', category: 'Tech', term: 'Term 3 (2026)' },
  { id: 'p12', name: 'Peer Tutoring Hub', description: 'Platform connecting student tutors with peers for academic support.', stage: 3, stageName: 'Developing', revenue: 0, expenses: 200, profit: -200, donation: 0, donationPercent: 15, team: [{ role: 'Marketing', members: ['Seungmin C.'] }, { role: 'Production', members: ['Amy L.'] }, { role: 'Finance', members: ['Junho K.'] }, { role: 'Design', members: ['Maya P.'] }], image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop', startDate: '2025-05-10', category: 'Education', term: 'Term 2 (2025)' },
  { id: 'p13', name: 'Upcycled Fashion', description: 'Transformed second-hand clothing into trendy pieces, promoting circular fashion.', stage: 6, stageName: 'Sales', revenue: 1800, expenses: 540, profit: 1260, donation: 252, donationPercent: 20, team: [{ role: 'Marketing', members: ['Chaerin K.'] }, { role: 'Production', members: ['Zoe A.'] }, { role: 'Finance', members: ['Minsu L.'] }, { role: 'Design', members: ['Harper J.'] }], image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop', startDate: '2025-01-08', category: 'Fashion', term: 'Term 1 (2025)' },
  { id: 'p14', name: 'Student Recipe Book', description: 'Collaborative cookbook with 50+ budget-friendly recipes from students worldwide.', stage: 7, stageName: 'Completed', revenue: 950, expenses: 380, profit: 570, donation: 142, donationPercent: 25, team: [{ role: 'Marketing', members: ['Bora S.'] }, { role: 'Production', members: ['Henry C.'] }, { role: 'Finance', members: ['Eunbi Y.'] }, { role: 'Design', members: ['Nathan R.'] }], image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&h=400&fit=crop', startDate: '2024-10-15', category: 'Food & Beverage', term: 'Term 4 (2026)' },
  { id: 'p15', name: 'Wellness Kit', description: 'Self-care packages with aromatherapy, skincare, and mindfulness guides.', stage: 5, stageName: 'Production', revenue: 700, expenses: 350, profit: 350, donation: 70, donationPercent: 20, team: [{ role: 'Marketing', members: ['Sohee P.'] }, { role: 'Production', members: ['Lily M.'] }, { role: 'Finance', members: ['Taehyung K.'] }, { role: 'Design', members: ['Aria S.'] }], image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop', startDate: '2025-04-01', category: 'Lifestyle', term: 'Term 2 (2025)' },
  { id: 'p16', name: 'Photography Service', description: 'Professional portrait and event photography by student photographers.', stage: 4, stageName: 'Testing', revenue: 400, expenses: 160, profit: 240, donation: 48, donationPercent: 20, team: [{ role: 'Marketing', members: ['Yeji K.'] }, { role: 'Production', members: ['Jack D.'] }, { role: 'Finance', members: ['Minjae S.'] }, { role: 'Design', members: ['Scarlett W.'] }], image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600&h=400&fit=crop', startDate: '2025-03-15', category: 'Services', term: 'Term 2 (2025)' },
  { id: 'p17', name: 'Language Exchange Hub', description: 'Cross-cultural language learning community for conversation practice.', stage: 1, stageName: 'Planning', revenue: 0, expenses: 50, profit: -50, donation: 0, donationPercent: 10, team: [{ role: 'Marketing', members: ['Jihye L.'] }, { role: 'Production', members: ['Sam T.'] }, { role: 'Finance', members: ['Kyungmin P.'] }, { role: 'Design', members: ['Mia K.'] }], image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop', startDate: '2025-06-15', category: 'Education', term: 'Term 3 (2026)' },
  { id: 'p18', name: 'Board Game Night Kit', description: 'Custom-designed party game sets with original illustrations.', stage: 6, stageName: 'Sales', revenue: 1100, expenses: 550, profit: 550, donation: 110, donationPercent: 20, team: [{ role: 'Marketing', members: ['Siwoo J.'] }, { role: 'Production', members: ['Emily R.'] }, { role: 'Finance', members: ['Donghyun C.'] }, { role: 'Design', members: ['Luna B.'] }], image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&h=400&fit=crop', startDate: '2025-02-20', category: 'Entertainment', term: 'Term 1 (2025)' },
  { id: 'p19', name: 'Plant Care Starter Set', description: 'Beginner-friendly indoor plant kits with pots, soil, seeds, and care guides.', stage: 5, stageName: 'Production', revenue: 500, expenses: 300, profit: 200, donation: 40, donationPercent: 20, team: [{ role: 'Marketing', members: ['Yerin K.'] }, { role: 'Production', members: ['Theo L.'] }, { role: 'Finance', members: ['Gayoung S.'] }, { role: 'Design', members: ['Felix H.'] }], image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600&h=400&fit=crop', startDate: '2025-04-22', category: 'Lifestyle', term: 'Term 2 (2025)' },
  { id: 'p20', name: 'Custom Phone Cases', description: 'Personalized phone cases with student-created digital art and premium materials.', stage: 7, stageName: 'Completed', revenue: 2800, expenses: 1120, profit: 1680, donation: 504, donationPercent: 30, team: [{ role: 'Marketing', members: ['Jimin N.'] }, { role: 'Production', members: ['Alex G.'] }, { role: 'Finance', members: ['Soyoung K.'] }, { role: 'Design', members: ['Ruby D.'] }], image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&h=400&fit=crop', startDate: '2024-12-01', category: 'Tech', term: 'Term 4 (2026)' },
  { id: 'p21', name: 'Study Snack Subscription', description: 'Weekly delivery of curated healthy snacks for study sessions.', stage: 3, stageName: 'Developing', revenue: 0, expenses: 280, profit: -280, donation: 0, donationPercent: 15, team: [{ role: 'Marketing', members: ['Hyejin L.'] }, { role: 'Production', members: ['Will P.'] }, { role: 'Finance', members: ['Sangwoo B.'] }, { role: 'Design', members: ['Cora M.'] }], image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop', startDate: '2025-05-28', category: 'Food & Beverage', term: 'Term 3 (2026)' },
  { id: 'p22', name: 'Campus Newsletter', description: 'Weekly digital publication covering student achievements and startup stories.', stage: 4, stageName: 'Testing', revenue: 300, expenses: 100, profit: 200, donation: 30, donationPercent: 15, team: [{ role: 'Marketing', members: ['Yoonah C.'] }, { role: 'Production', members: ['Ben S.'] }, { role: 'Finance', members: ['Jieun M.'] }, { role: 'Design', members: ['Iris T.'] }], image: 'https://images.unsplash.com/photo-1504711434969-e33886168d9c?w=600&h=400&fit=crop', startDate: '2025-04-08', category: 'Media', term: 'Term 2 (2025)' },
];

export const products: Product[] = [
  { id: 'prod1', name: 'Eco Canvas Tote', description: 'Reusable canvas tote with original student artwork. Durable, stylish, and eco-friendly.', price: 12.99, image: 'https://images.unsplash.com/photo-1597484661973-ee6cd0b6482c?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1597484661973-ee6cd0b6482c?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&h=600&fit=crop'], category: 'Accessories', inventory: 45, isPreOrder: false, projectId: 'p1', term: 'Term 1 (2025)', status: 'available' },
  { id: 'prod2', name: 'Premium Student Planner', description: 'Academic year planner with productivity templates, goal trackers, and monthly reviews. Designed by our Design team for maximum usability.', price: 18.99, image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=600&fit=crop'], category: 'Stationery', inventory: 30, isPreOrder: false, projectId: 'p2', term: 'Term 1 (2025)', status: 'available' },
  { id: 'prod3', name: 'Campus Blend Coffee', description: 'Ethically sourced medium roast with notes of chocolate and citrus. 250g bag, roasted fresh by local partners.', price: 14.99, image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=600&fit=crop'], category: 'Food & Beverage', inventory: 60, isPreOrder: false, projectId: 'p3', term: 'Term 4 (2026)', status: 'available' },
  { id: 'prod4', name: 'Artisan Soy Candle', description: 'Hand-poured soy wax candle with seasonal campus-inspired scents. 8oz jar, burns for 40+ hours.', price: 14.50, image: 'https://images.unsplash.com/photo-1602607469288-db8e02f6fee3?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1602607469288-db8e02f6fee3?w=800&h=600&fit=crop'], category: 'Lifestyle', inventory: 25, isPreOrder: false, projectId: 'p4', term: 'Term 1 (2025)', status: 'available' },
  { id: 'prod5', name: 'Bamboo Phone Stand', description: 'Minimalist bamboo desk phone stand with cable management slot. Fits all phone sizes.', price: 9.99, image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&h=600&fit=crop'], category: 'Tech', inventory: 18, isPreOrder: false, projectId: 'p5', term: 'Term 2 (2025)', status: 'available' },
  { id: 'prod6', name: 'Minimalist Beaded Bracelet', description: 'Handcrafted bracelet with sustainable stone beads and adjustable cord.', price: 8.50, image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&h=600&fit=crop'], category: 'Fashion', inventory: 40, isPreOrder: false, projectId: 'p6', term: 'Term 1 (2025)', status: 'available' },
  { id: 'prod7', name: 'Recycled Paper Notebook', description: 'A5 notebook made from 100% recycled paper with plantable seed cover.', price: 6.99, image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&h=600&fit=crop'], category: 'Stationery', inventory: 0, isPreOrder: false, projectId: 'p7', term: 'Term 2 (2025)', status: 'in-production' },
  { id: 'prod8', name: 'School Spirit Hoodie', description: 'Premium cotton-blend hoodie with modern school branding. Unisex sizing S-XXL.', price: 34.99, image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&h=600&fit=crop'], category: 'Apparel', inventory: 0, isPreOrder: false, projectId: 'p8', term: 'Term 3 (2026)', status: 'sold-out' },
  { id: 'prod9', name: 'Organic Trail Mix Box', description: 'Curated box of 6 organic trail mix pouches with dried fruits and nuts.', price: 11.99, image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=600&fit=crop'], category: 'Food & Beverage', inventory: 35, isPreOrder: false, projectId: 'p9', term: 'Term 1 (2025)', status: 'available' },
  { id: 'prod10', name: 'Digital Art Print — Bloom', description: 'Limited edition giclee print on archival paper. Signed and numbered. 11x14 inches.', price: 15.00, image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=600&fit=crop'], category: 'Art', inventory: 15, isPreOrder: false, projectId: 'p10', term: 'Term 2 (2025)', status: 'available' },
  { id: 'prod11', name: 'Upcycled Denim Pouch', description: 'Unique zippered pouch made from reclaimed denim. Each piece is one-of-a-kind.', price: 13.50, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop'], category: 'Fashion', inventory: 12, isPreOrder: false, projectId: 'p13', term: 'Term 1 (2025)', status: 'available' },
  { id: 'prod12', name: 'Student Recipe Book', description: 'Collaborative cookbook with 50+ budget-friendly recipes from students worldwide.', price: 12.00, image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&h=600&fit=crop'], category: 'Books', inventory: 40, isPreOrder: false, projectId: 'p14', term: 'Term 4 (2026)', status: 'available' },
  { id: 'prod13', name: 'Wellness Essential Kit', description: 'Self-care set with lavender balm, herbal tea, and a mindfulness journal.', price: 22.99, image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=600&fit=crop'], category: 'Lifestyle', inventory: 22, isPreOrder: false, projectId: 'p15', term: 'Term 2 (2025)', status: 'available' },
  { id: 'prod14', name: 'Custom Phone Case', description: 'Personalized phone case with student digital art. Available for iPhone and Samsung.', price: 16.99, image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&h=600&fit=crop'], category: 'Tech', inventory: 50, isPreOrder: false, projectId: 'p20', term: 'Term 4 (2026)', status: 'available' },
  { id: 'prod15', name: 'Board Game Night Set', description: 'Original party game with custom illustrations. 2-8 players, ages 14+.', price: 24.99, image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&h=600&fit=crop'], category: 'Entertainment', inventory: 0, isPreOrder: true, projectId: 'p18', term: 'Term 1 (2025)', status: 'in-production' },
  { id: 'prod16', name: 'Plant Care Starter Kit', description: 'Indoor herb garden kit with ceramic pot, organic soil, seeds, and illustrated guide.', price: 19.99, image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=500&h=500&fit=crop', images: ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&h=600&fit=crop'], category: 'Lifestyle', inventory: 28, isPreOrder: false, projectId: 'p19', term: 'Term 2 (2025)', status: 'available' },
];

export const mockMember: MemberProfile = {
  name: 'Jisoo Kim',
  email: 'jisoo.kim@school.edu',
  role: 'Team Lead',
  team: 'Marketing',
  attendance: 18,
  totalMeetings: 20,
  contributions: 12,
  joinDate: '2025-09-01',
};

export const mockMeetings = [
  { id: 'm1', date: '2026-03-25', status: 'present' as const, feedback: 'Great presentation on Q1 marketing metrics. Keep up the excellent work.' },
  { id: 'm2', date: '2026-03-18', status: 'present' as const, feedback: '' },
  { id: 'm3', date: '2026-03-11', status: 'absent' as const, feedback: 'Missed sprint review. Please review meeting notes and follow up with your team lead.' },
  { id: 'm4', date: '2026-03-04', status: 'present' as const, feedback: 'Led the brainstorming session effectively. Good leadership initiative.' },
  { id: 'm5', date: '2026-02-25', status: 'present' as const, feedback: '' },
  { id: 'm6', date: '2026-02-18', status: 'present' as const, feedback: 'Submitted budget report on time. Clear and well-organized.' },
  { id: 'm7', date: '2026-02-11', status: 'present' as const, feedback: '' },
  { id: 'm8', date: '2026-02-04', status: 'absent' as const, feedback: 'Excused absence. Make sure to catch up on the product roadmap changes.' },
  { id: 'm9', date: '2026-01-28', status: 'present' as const, feedback: 'Excellent contribution to the marketing strategy discussion.' },
  { id: 'm10', date: '2026-01-21', status: 'present' as const, feedback: '' },
];

export const revenueChartData = [
  { month: 'Sep', revenue: 800, expenses: 600 },
  { month: 'Oct', revenue: 1200, expenses: 700 },
  { month: 'Nov', revenue: 1800, expenses: 900 },
  { month: 'Dec', revenue: 2400, expenses: 1100 },
  { month: 'Jan', revenue: 3200, expenses: 1400 },
  { month: 'Feb', revenue: 4100, expenses: 1600 },
  { month: 'Mar', revenue: 5200, expenses: 2000 },
  { month: 'Apr', revenue: 6800, expenses: 2400 },
  { month: 'May', revenue: 8200, expenses: 2800 },
  { month: 'Jun', revenue: 9600, expenses: 3200 },
];

export const donationByProject = [
  { name: 'School Merch', value: 675 },
  { name: 'Custom Cases', value: 504 },
  { name: 'Coffee Co.', value: 480 },
  { name: 'Jewelry', value: 378 },
  { name: 'EcoBag', value: 360 },
  { name: 'Upcycled', value: 252 },
  { name: 'Planner', value: 216 },
  { name: 'Others', value: 1335 },
];

export const memberGrowth = [
  { month: "Sep '24", members: 12 },
  { month: 'Oct', members: 18 },
  { month: 'Nov', members: 24 },
  { month: 'Dec', members: 30 },
  { month: "Jan '25", members: 38 },
  { month: 'Feb', members: 46 },
  { month: 'Mar', members: 55 },
  { month: 'Apr', members: 64 },
  { month: 'May', members: 74 },
  { month: 'Jun', members: 84 },
];
