export const teamPageCopy = {
  en: {
    nav: 'Team',
    homeKicker: 'People',
    homeTitle: 'The people behind the work.',
    homeSubtitle:
      'Student Startups becomes credible when the people carrying the work are visible.',
    homeCta: 'View Team',
    pageKicker: 'People',
    pageTitle: 'A student-built ecosystem with real contributors.',
    pageSubtitle:
      'Student Startups is not a single resume site. It is a working network of students building products, taking responsibility, and leaving a record of serious work.',
    founderLabel: 'Founder',
    featuredTitle: 'Featured contributors',
    featuredSubtitle:
      'Selected members whose work, leadership, and consistency shape the platform.',
    directoryTitle: 'Team directory',
    directorySubtitle:
      'A shared record of the people building, operating, and improving Student Startups.',
    allFilter: 'All',
    allRoles: 'All roles',
    allTeams: 'All teams',
    allActivity: 'All activity',
    recentlyActive: 'Recently active',
    joinedPrefix: 'Joined',
    projectsStat: 'Projects',
    collaborationsStat: 'Collaborations',
    eventsStat: 'Events',
    contributionsStat: 'Contribution points',
    viewProfile: 'View profile',
    noMembersTitle: 'Profiles will appear here.',
    noMembersBody:
      'Once member records are available, this page will present the people behind the platform.',
    modal: {
      close: 'Close',
      roleLabel: 'Role',
      teamLabel: 'Team',
      about: 'About',
      contributions: 'Contributions to the platform',
      projects: 'Projects Contributed To',
      leadership: 'Leadership & Initiative',
      built: "What I've Built",
      impact: 'Impact',
      goals: 'Current Goals',
      skills: 'Skills Developed Through Student Startups',
      interests: 'Interests',
      timeline: 'Timeline of Involvement',
      contact: 'Links',
      noProjects: 'No public project record yet.',
      noTimeline: 'Timeline entries will appear as work is recorded.',
    },
  },
  ko: {
    nav: '팀',
    homeKicker: '사람들',
    homeTitle: '이 플랫폼을 움직이는 사람들.',
    homeSubtitle:
      'Student Startups의 신뢰감은 결과만이 아니라 그 결과를 만든 사람들까지 드러날 때 더 분명해집니다.',
    homeCta: '팀 보기',
    pageKicker: '사람들',
    pageTitle: '학생이 직접 만든 생태계, 그리고 그 안의 기여자들.',
    pageSubtitle:
      'Student Startups는 한 사람의 이력 사이트가 아닙니다. 제품을 만들고, 운영을 맡고, 결과를 남기는 학생들이 함께 쌓아가는 실제 시스템입니다.',
    founderLabel: 'Founder',
    featuredTitle: '주요 기여자',
    featuredSubtitle:
      '플랫폼의 기준, 리더십, 실행력을 만들어가는 멤버들을 선별해 보여줍니다.',
    directoryTitle: '팀 디렉터리',
    directorySubtitle:
      'Student Startups를 만들고 운영하며 다듬고 있는 사람들의 기록입니다.',
    allFilter: '전체',
    allRoles: '전체 역할',
    allTeams: '전체 팀',
    allActivity: '전체 활동',
    recentlyActive: '최근 활동',
    joinedPrefix: '합류',
    projectsStat: '프로젝트',
    collaborationsStat: '협업',
    eventsStat: '참여 기록',
    contributionsStat: '기여 포인트',
    viewProfile: '프로필 보기',
    noMembersTitle: '프로필이 곧 표시됩니다.',
    noMembersBody:
      '멤버 기록이 준비되면 이 페이지에서 플랫폼을 만든 사람들을 볼 수 있습니다.',
    modal: {
      close: '닫기',
      roleLabel: '역할',
      teamLabel: '팀',
      about: '소개',
      contributions: '플랫폼에 기여한 일',
      projects: '참여한 프로젝트',
      leadership: '리더십과 주도성',
      built: '직접 만든 것',
      impact: '영향',
      goals: '현재 목표',
      skills: 'Student Startups를 통해 쌓은 역량',
      interests: '관심 분야',
      timeline: '참여 타임라인',
      contact: '링크',
      noProjects: '공개된 프로젝트 기록이 아직 없습니다.',
      noTimeline: '기록이 쌓이면 이곳에 타임라인이 보입니다.',
    },
  },
} as const;

export type TeamPageLocale = keyof typeof teamPageCopy;
